### ISSUE TITLE
str method does not work for NumpyVectorArrayView

### ISSUE THREAD

**Issue by pmli** [pymor/pymor#1057]
Here is an example:

```pycon
>>> from pymor.vectorarrays.numpy import NumpyVectorSpace
>>> v = NumpyVectorSpace(5).zeros(1)
>>> v
NumpyVectorArray([[0. 0. 0. 0. 0.]], NumpyVectorSpace(5))
>>> print(v)
[[0. 0. 0. 0. 0.]]
>>> v[0]
NumpyVectorArrayView([[0. 0. 0. 0. 0.]], NumpyVectorSpace(5))
>>> print(v[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mp/Documents/codes/pymor/src/pymor/vectorarrays/numpy.py", line 262, in __str__
    return self._array[:self._len].__str__()
AttributeError: 'NumpyVectorArrayView' object has no attribute '_array'
```

**Comment by renefritze** [comment]
Since this was apparently not covered in tests, I've add a stupid one in the issue_1057 branch. A bugfix should base on that branch and also should be backported.

**Comment by renefritze** [comment]
https://github.com/pymor/pymor/commit/e71540cbb55730b1d831b0dad9f151ed4983ca2c

**Comment by pmli** [comment]
Thanks, @renefritze. I've opened a PR now.
