### ISSUE TITLE
Installation of current development version not working

### ISSUE THREAD

**Issue by HenKlei** [pymor/pymor#1059]
According to the readme, it should be possible to install the current development version via
```
pip install git+https://github.com/pymor/pymor#egg=pymor[full]
```

In a clean virtualenv, without having anything installed, I tried this command and got the following error:
```
Collecting pymor[full]
  Cloning https://github.com/pymor/pymor to /tmp/pip-install-7x52d4ay/pymor
  Running command git clone -q https://github.com/pymor/pymor /tmp/pip-install-7x52d4ay/pymor
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/h_klei18/test-venv/bin/python /home/h_klei18/test-venv/lib/python3.8/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpgt4ggew1
         cwd: /tmp/pip-install-7x52d4ay/pymor
    Complete output (56 lines):
    Traceback (most recent call last):
      File "/tmp/pip-build-env-u_wpbnm7/overlay/lib/python3.8/site-packages/numpy/core/__init__.py", line 22, in <module>
        from . import multiarray
      File "/tmp/pip-build-env-u_wpbnm7/overlay/lib/python3.8/site-packages/numpy/core/multiarray.py", line 12, in <module>
        from . import overrides
      File "/tmp/pip-build-env-u_wpbnm7/overlay/lib/python3.8/site-packages/numpy/core/overrides.py", line 7, in <module>
        from numpy.core._multiarray_umath import (
    ImportError: /tmp/pip-build-env-u_wpbnm7/overlay/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/h_klei18/test-venv/lib/python3.8/site-packages/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/h_klei18/test-venv/lib/python3.8/site-packages/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/h_klei18/test-venv/lib/python3.8/site-packages/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-u_wpbnm7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-u_wpbnm7/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 185, in <module>
        setup_package()
      File "setup.py", line 152, in setup_package
        _setup(
      File "setup.py", line 117, in _setup
        _numpy_monkey()
      File "setup.py", line 45, in _numpy_monkey
        from numpy.distutils.misc_util import appendpath
      File "/tmp/pip-build-env-u_wpbnm7/overlay/lib/python3.8/site-packages/numpy/__init__.py", line 140, in <module>
        from . import core
      File "/tmp/pip-build-env-u_wpbnm7/overlay/lib/python3.8/site-packages/numpy/core/__init__.py", line 48, in <module>
        raise ImportError(msg)
    ImportError:
    
    IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
    
    Importing the numpy C-extensions failed. This error can happen for
    many reasons, often due to issues with your setup or how NumPy was
    installed.
    
    We have compiled some common reasons and troubleshooting tips at:
    
        https://numpy.org/devdocs/user/troubleshooting-importerror.html
    
    Please note and check the following:
    
      * The Python version is: Python3.8 from "/home/h_klei18/test-venv/bin/python"
      * The NumPy version is: "1.19.1"
    
    and make sure that they are the versions you expect.
    Please carefully study the documentation linked above for further help.
    
    Original error was: /tmp/pip-build-env-u_wpbnm7/overlay/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so: failed to map segment from shared object
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/h_klei18/test-venv/bin/python /home/h_klei18/test-venv/lib/python3.8/site-packages/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpgt4ggew1 Check the logs for full command output.
```

Running `pip freeze --all` afterwards gives:
```
appdirs==1.4.3
CacheControl==0.12.6
certifi==2019.11.28
chardet==3.0.4
colorama==0.4.3
contextlib2==0.6.0
distlib==0.3.0
distro==1.4.0
html5lib==1.0.1
idna==2.8
ipaddr==2.2.0
lockfile==0.12.2
msgpack==0.6.2
packaging==20.3
pep517==0.8.2
pip==20.0.2
pkg-resources==0.0.0
progress==1.5
pyparsing==2.4.6
pytoml==0.1.21
requests==2.22.0
retrying==1.3.3
setuptools==44.0.0
six==1.14.0
urllib3==1.25.8
webencodings==0.5.1
wheel==0.34.2
```

**Comment by TiKeil** [comment]
That doesn't happen on my machine (Mac OS)

**Comment by renefritze** [comment]
Yeah, I cannot yet replicate this either. It _should_ be a numpy issue.

**Comment by TiKeil** [comment]
I tried both, first installing numpy (with and without pip upgrade) or just installing pymor (with and without pip upgrade).
Works in any cases.

**Comment by renefritze** [comment]
So this issue happens on one of our compute servers. I can replicate this now. Fresh venv, install pymor -> boom. Install numpy, install pymor -> boom. There's some snafu with between the pep517 build mode and numpy.

**Comment by renefritze** [comment]
Only happens with the `git+https` url install, not with released wheel.

**Comment by HenKlei** [comment]
> So this issue happens on one of our compute servers. I can replicate this now. Fresh venv, install pymor -> boom. Install numpy, install pymor -> boom.

This is exactly how I produced this.

**Comment by renefritze** [comment]
Same thing happens with ` pip install git+https://github.com/scipy/scipy#egg=scipy` so it's not just us. And I think I found out what happens. My venv has numpy 1.19.1 installed. The helpful error message on scipy/pymor install for numpy import fail says:
```
...
      1. Check that you expected to use Python3.8 from "$HOME/.local/share/virtualenvs/foo-r-OLon9H/bin/python",
         and that you have no directories in your PATH or PYTHONPATH that can
         interfere with the Python and numpy version "1.17.3" you're trying to use.
...
```
Guess what?
```
apt show python3-numpy
Package: python3-numpy
Version: 1:1.17.4-5ubuntu3
```

So not sure if it's pip or setuptools problem, but it's def. not something for us to fix.

If you want @HenKlei, you could try to find an issue upstream and failing that try to report one.

**Comment by renefritze** [comment]
As another data point: Do you have any global numpy install that could be picked up during pymor install, @TiKeil ?

**Comment by TiKeil** [comment]
Yes I do have a global numpy (version 1.18.2). I am afraid I break my computer by deinstalling it.

**Comment by renefritze** [comment]
No need, just curious. It's another layer of weird why you don't get the same issue then though. Is it also a wheel install maybe?

**Comment by renefritze** [comment]
In a surprising turn of events, #1065 will actually prevent this issue. The reason we only see this on our one compute server is a newer setuptools there. This also explains why @TiKeil has no problem. To confirm, @HenKlei, run `pip install setuptools==41.4.0` and then install from git url.
