### ISSUE TITLE
1D visualization broken

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#1209]
Calling

```
elliptic_oned.py 0 100
```

leads to

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/stephan/Repos/pymor/src/pymor/discretizers/builtin/gui/qt.py", line 186, in _doit
    main_window = factory()
  File "/home/stephan/Repos/pymor/src/pymor/discretizers/builtin/gui/qt.py", line 442, in <lambda>
    _launch_qt_app(lambda: MainWindow(grid, U, codim, title=title, legend=legend, separate_plots=separate_plots), block)
  File "/home/stephan/Repos/pymor/src/pymor/discretizers/builtin/gui/qt.py", line 438, in __init__
    separate_plots=separate_plots)
TypeError: __init__() missing 1 required positional argument: 'grid'
```

**Comment by renefritze** [comment]
Yet another instance of https://github.com/pymor/pymor/issues/1178
