### ISSUE TITLE
Can't run the thermalblock example after a fresh install

### ISSUE THREAD

**Issue by j-henning** [pymor/pymor#1533]
I am using Python 3.8 with a virtual enviroment on Ubuntu (inside a VM). 

After installing the latest release version of PyMOR via

```
pip install --upgrade pip
pip install git+https://github.com/pymor/pymor@2021.2.x#egg=pymor[full]
```

and running the thermalblock example via

`pymor-demo thermalblock --plot-err --plot-solutions 3 2 3 32`

I get the following error

```
Traceback (most recent call last):
  File "/home/atr/Documents/pyMOR/virtuelenv/bin/pymor-demo", line 8, in <module>
  File "/home/atr/Documents/pyMOR/virtuelenv/lib/python3.8/site-packages/pymor/scripts/pymor_demo.py", line 36, in run
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/atr/Documents/pyMOR/virtuelenv/lib/python3.8/site-packages/pymordemos/thermalblock_gui.py", line 27, in <module>
  File "/home/atr/Documents/pyMOR/virtuelenv/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
  File "/home/atr/Documents/pyMOR/virtuelenv/lib/python3.8/site-packages/pymor/discretizers/builtin/gui/gl.py", line 21, in <module>
  File "/home/atr/Documents/pyMOR/virtuelenv/lib/python3.8/site-packages/pymor/core/config.py", line 179, in __getattr__
  File "/home/atr/Documents/pyMOR/virtuelenv/lib/python3.8/site-packages/pymor/core/config.py", line 148, in <lambda>
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
  File "/home/atr/Documents/pyMOR/virtuelenv/lib/python3.8/site-packages/qtpy/QtOpenGL.py", line 14, in <module>
NameError: name 'PYQT6' is not defined

```
The error also occurs if I install pyMOR via

`pip install pymor[full]`

**Comment by renefritze** [comment]
Right. This is due to a [bug in qtpy](https://github.com/spyder-ide/qtpy/pull/307). I've [blocked](https://github.com/pymor/pymor/commit/ef72f92ae7910a80be9cb1c81c4d384e75015b5e) the broken version in main, but didn't think to backport to the release. I was hoping a bugfix release in qtpy would happen faster. 
Thank you for bringing this to my attention again @j-henning!

As a workaround you can downgrade qtpy:
```
python3 -m pip install qtpy==1.9.0
```
After that the demo should work.
