### ISSUE TITLE
Minimal Fenics Version supported

### ISSUE THREAD

**Issue by renemilk** [pymor/pymor#167]
I took the liberty to "split" the last two comments from #149:
Me:
> Our tests do work with fenics 1.3.0 btw, I've check with a default Ubuntu 14.04 machine.

@ftalbrecht:
> Very nice. Since you have this setup lying around :), could you also do a quick test of the `thermalblock_fenics.py` demo (e.g., with `-e 2 2 2 20` arguments) and compare the results to #146.

**Comment by renemilk** [comment]
Well, turns out the tests didn't actually run with fenics support. So currently, nope can't do and no idea wrt minimal version.

**Comment by ftalbrecht** [comment]
:( Could you report the outcome of the thermalblock demo call, if there is any useful information (e.g., do we just have to adapt our side of the dolfin bindings or does it not work at all)?

**Comment by renemilk** [comment]
```
(venve)┐ (r_milk01@OORYL) [15:24:05|Thu Oct 08] [master] [~/projekte/uni/pymor/src] 
└───> ./pymordemos/thermalblock_fenics.py -e 2 2 2 20
Loading pymor version 0.3.0rc0-520-g3524073
Discretize ...
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling DOLFIN just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.
Traceback (most recent call last):
  File "./pymordemos/thermalblock_fenics.py", line 264, in <module>
    thermalblock_demo(args)
  File "./pymordemos/thermalblock_fenics.py", line 156, in thermalblock_demo
    discretization = discretize(args)
  File "./pymordemos/thermalblock_fenics.py", line 115, in discretize
    from pymor.gui.fenics import FenicsVisualizer
  File "/data/home/r_milk01/projekte/uni/pymor/src/pymor/gui/fenics.py", line 16, in <module>
    from pymor.vectorarrays.fenics import FenicsVector
  File "/data/home/r_milk01/projekte/uni/pymor/src/pymor/vectorarrays/fenics.py", line 119, in <module>
    def FenicsVectorSpace(dim, mpi_comm=df.mpi_comm_world()):
AttributeError: 'module' object has no attribute 'mpi_comm_world'

```

**Comment by sdrave** [comment]
The dolfin changelog contains the following for version 1.4.0:

```
 - Use MPI communicator in interfaces. Permits the creation of distributed and
	local objects, e.g. Meshes.
```

This is used extensively in the pyMOR wrappers, so we will need at least 1.4.0.

**Comment by renemilk** [comment]
Hmm. So using 1.3.x in #168 wouldn't be any good even if I could.
