### ISSUE TITLE
The function output() cannot be called on a sum/difference of LTIModels

### ISSUE THREAD

**Issue by niklasreich** [pymor/pymor#2187]
If one defines a LTIModel as a sum/difference of LTIModels with identical input and output dimension the function output() gives a NotImplementedError although this should be possible.
This bug can be reproced for example by defining an "error" model as `err = fom - rom` where `fom` and `rom` are LTIModels and `rom` is the reduced model of `fom` via `MTReductor()`. Then `err.output(input=input)` gives the described error.

**Comment by sdrave** [comment]
@pmli, can you take a look?

**Comment by pmli** [comment]
Minimal working example:

```python
import numpy as np

from pymor.algorithms.timestepping import ExplicitEulerTimeStepper
from pymor.models.iosys import LTIModel

m = LTIModel.from_matrices(-np.eye(1), np.eye(1), np.eye(1),
                           T=1, time_stepper=ExplicitEulerTimeStepper(10))
print(m.output(input='sin(t)'))

s = m + m
print(f'{s.D=}')
print(s.output(input='sin(t)'))
```

Output:

```
00:00 LTIModel: Solving LTIModel for {input: SymbolicExpressionFunction: t -> [sin(t)[0]](0) = [0.0]} ...
[[0.        ]
 [0.00998334]
 [0.02885194]
 [0.05551877]
 [0.08890872]
 [0.12796041]
 [0.17162861]
 [0.21888752]
 [0.26873438]
 [0.32019363]
 [0.37232137]]
s.D=LincombOperator(
    (ZeroOperator(NumpyVectorSpace(1), NumpyVectorSpace(1)), ZeroOperator(NumpyVectorSpace(1), NumpyVectorSpace(1))),
    (1.0, 1.0))
00:00 LTIModel: Solving LTIModel for {input: SymbolicExpressionFunction: t -> [sin(t)[0]](0) = [0.0]} ...
Traceback (most recent call last):
  File "/.../src/pymor/models/interface.py", line 505, in output
    data = self.compute(
  File "/.../src/pymor/models/interface.py", line 355, in compute
    data = self._compute(solution=solution, output=output,
  File "/.../src/pymor/models/iosys.py", line 660, in _compute
    raise NotImplementedError
NotImplementedError
```

---

I see two ways to fix this:

1. call `assemble` on `D` in `__add__` and `__neg__` of `LTIModel` (easy fix, but might not work in general),
2. implement the computation of $D u(t)$ (requires figuring out how to pass $t$ from the time stepper to $D u(t)$).

**Comment by sdrave** [comment]
Calling `assemble` will not work as you need parameter values for that. I think we should call `contract`. Regarding 2., one would need to replace the `time_stepper.solve` call by a loop over `time_stepper.iterate`. This also would have the advantage, that the state space trajectory does not need to be stored in memory when only the output is requested. Probably we should implement both ..

**Comment by pmli** [comment]
I confirm that #2203 fixes this. The MWE above produces

```
00:00 LTIModel: Solving LTIModel for {input: ExpressionFunction: t -> sin(t)(0) = [0.0]} ...
[[0.        ]
 [0.00998334]
 [0.02885194]
 [0.05551877]
 [0.08890872]
 [0.12796041]
 [0.17162861]
 [0.21888752]
 [0.26873438]
 [0.32019363]
 [0.37232137]]
s.D=LincombOperator(
    (ZeroOperator(NumpyVectorSpace(1), NumpyVectorSpace(1)), ZeroOperator(NumpyVectorSpace(1), NumpyVectorSpace(1))),
    (1.0, 1.0))
00:00 LTIModel: Solving LTIModel for {input: ExpressionFunction: t -> sin(t)(0) = [0.0]} ...
[[0.        ]
 [0.01996668]
 [0.05770388]
 [0.11103753]
 [0.17781745]
 [0.25592081]
 [0.34325723]
 [0.43777504]
 [0.53746875]
 [0.64038726]
 [0.74464273]]
```
