### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by JasonETurner** [pymor/pymor#383]
Issue installing pyMOR. pip can throws an error code during the installation process. I am hoping to use pyMOR on macintosh with python 3.6.3 downloaded using homebrew (with numpy, scipy and others downloaded using pip3). Pasted below is the output from the terminal window:

| => pip3 install pymor[full]
Collecting pymor[full]
  Using cached pymor-0.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "/private/var/folders/79/h5bg5n5j15j3fxfck5zw08qw0000gn/T/pip-build-ne5jyete/pymor/setup.py", line 102, in write_version
        '--tags', '--candidates', '20', '--match', '*.*.*']).strip()
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--candidates', '20', '--match', '*.*.*']' returned non-zero exit status 128.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/79/h5bg5n5j15j3fxfck5zw08qw0000gn/T/pip-build-ne5jyete/pymor/setup.py", line 221, in <module>
        setup_package()
      File "/private/var/folders/79/h5bg5n5j15j3fxfck5zw08qw0000gn/T/pip-build-ne5jyete/pymor/setup.py", line 175, in setup_package
        revstring = write_version()
      File "/private/var/folders/79/h5bg5n5j15j3fxfck5zw08qw0000gn/T/pip-build-ne5jyete/pymor/setup.py", line 108, in write_version
        execfile(filename, loc, loc)
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/79/h5bg5n5j15j3fxfck5zw08qw0000gn/T/pip-build-ne5jyete/pymor/
___________

**Comment by renemilk** [comment]
Hi! pyMOR 0.4.2 is only compatible with python 2.7. We've merged python 3 support only after that release. If you install from github master, that should work with python 3 

```pip3 install git+https://github.com/pymor/pymor```

**Comment by JasonETurner** [comment]
Thank you! I had to sudo- as well.
