### ISSUE TITLE
Document that demos require pymor[full]

### ISSUE THREAD

**Issue by sdrave** [pymor/pymor#836]
I think that users are often surprised that `pip install pymor` yields a pyMOR installation with unusable demo scripts. At least, we should provide meaningful error messages. E.g. running

```bash
pymor-demo burgers 1
```

currently yields

```
Setup Problem ...
Discretize ...
Traceback (most recent call last):
  File "/home/stephan/.virtualenvs/foo/bin/pymor-demo", line 48, in <module>
    _run(modules[shorts.index(sys.argv[1])])
  File "/home/stephan/.virtualenvs/foo/bin/pymor-demo", line 23, in _run
    runpy.run_module(module, init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymordemos/burgers.py", line 90, in <module>
    burgers_demo(args)
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymordemos/burgers.py", line 72, in burgers_demo
    nt=args['--nt']
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymor/discretizers/fv.py", line 283, in discretize_instationary_fv
    boundary_info=boundary_info)
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymor/discretizers/fv.py", line 183, in discretize_stationary_fv
    visualizer = PatchVisualizer(grid=grid, bounding_box=grid.bounding_box(), codim=0)
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymor/gui/visualizers.py", line 38, in __init__
    backend = backend or ('jupyter' if is_jupyter() else None)
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymor/core/config.py", line 65, in is_jupyter
    from IPython import get_ipython
ModuleNotFoundError: No module named 'IPython'
```

due to #835 when no IPython is installed. After installing Ipython we get

```
Setup Problem ...
Discretize ...
Rect-Grid on domain [0,2] x [0,1]
x0-intervals: 120, x1-intervals: 60
faces: 7200, edges: 14400, vertices: 7200
The parameter type is {'exponent': ()}
Solving for exponent = 1.0 ... 
00:00 InstationaryModel: Solving burgers_problem_2d(1.0, 1.0, True, 'sin')_FV for {exponent: 1.0} ...
Solving took 1.2685604095458984s
Traceback (most recent call last):
  File "/home/stephan/.virtualenvs/foo/bin/pymor-demo", line 48, in <module>
    _run(modules[shorts.index(sys.argv[1])])
  File "/home/stephan/.virtualenvs/foo/bin/pymor-demo", line 23, in _run
    runpy.run_module(module, init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.7/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymordemos/burgers.py", line 90, in <module>
    burgers_demo(args)
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymordemos/burgers.py", line 84, in burgers_demo
    m.visualize(U)
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymor/models/basic.py", line 44, in visualize
    return self.visualizer.visualize(U, self, **kwargs)
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymor/gui/visualizers.py", line 91, in visualize
    from pymor.gui.qt import visualize_patch
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymor/gui/qt.py", line 21, in <module>
    from pymor.gui.gl import GLPatchWidget, ColorBarWidget
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymor/gui/gl.py", line 19, in <module>
    if config.HAVE_QT and config.HAVE_QTOPENGL and config.HAVE_GL:
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymor/core/config.py", line 128, in __getattr__
    version = _PACKAGES[package]()
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/pymor/core/config.py", line 57, in _get_qt_version
    import Qt
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/Qt.py", line 1874, in <module>
    _install()
  File "/home/stephan/.virtualenvs/foo/lib/python3.7/site-packages/Qt.py", line 1852, in _install
    our_submodule = getattr(Qt, name)
AttributeError: module 'Qt' has no attribute 'QtGui'
```

**Comment by renefritze** [comment]
It might be a good idea to actual install dependencies.py with pymor so we can check this from runtime.

**Comment by renefritze** [comment]
The second import error very much looks like a bug in `Qt.py` btw.

**Comment by sdrave** [comment]
@renefritze, what do you mean by that? You are probably right that `Qt.py` also should give a more helpful error message, but in this case I am pretty sure that the error is due to missing `pyqt/pyside`.

**Comment by sdrave** [comment]
Probably we need to fix `_get_qt_version`.

**Comment by renefritze** [comment]
The bug in `Qt.py` seems to happen if you got pyside installed, so you can import `QtCore`, but cannot load `QtGui`. For example due missing libGL.

**Comment by sdrave** [comment]
Can't reproduce the second error anymore. I now get a reasonable error message. So let's ignore it ..

**Comment by renefritze** [comment]
`Qt.py` updated from 1.2.3 to 1.2.4 just two days ago.
